on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      - run: pnpm install
      - run: pnpm ts:check
      - run: pnpm format:check